#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-asciidoctor-gradle-plugin
Version  : elease.1.5.3
Release  : 2
URL      : https://github.com/asciidoctor/asciidoctor-gradle-plugin/archive/release_1_5_3.tar.gz
Source0  : https://github.com/asciidoctor/asciidoctor-gradle-plugin/archive/release_1_5_3.tar.gz
Source1  : https://repo.gradle.org/gradle/libs-releases/org/asciidoctor/asciidoctor-gradle-plugin/1.5.3/asciidoctor-gradle-plugin-1.5.3.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/org/asciidoctor/asciidoctor-gradle-plugin/1.5.3/asciidoctor-gradle-plugin-1.5.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-asciidoctor-gradle-plugin-data = %{version}-%{release}
Requires: mvn-asciidoctor-gradle-plugin-license = %{version}-%{release}

%description
= Asciidoctor Gradle Plugin
Andres Almiray <https://github.com/aalmiray[@aalmiray]>
:version: 1.5.3-SNAPSHOT
:version-published: 1.5.3
:asciidoc-url: http://asciidoc.org
:asciidoctor-url: http://asciidoctor.org
:issues: https://github.com/asciidoctor/asciidoctor-maven-plugin/issues
:gradle-url: http://gradle.org/
:asciidoctor-maven-plugin: https://github.com/asciidoctor/asciidoctor-maven-plugin
:lightguard: https://github.com/LightGuard
:asciidoctorj: https://github.com/asciidoctor/asciidoctorj
:lordofthejars: https://github.com/lordofthejars
:asciidoctor-docs: http://asciidoctor.org/docs/
:project-name: asciidoctor-gradle-plugin
:project-full-path: asciidoctor/asciidoctor-gradle-plugin
:github-branch: master
:linkattrs:

%package data
Summary: data components for the mvn-asciidoctor-gradle-plugin package.
Group: Data

%description data
data components for the mvn-asciidoctor-gradle-plugin package.


%package license
Summary: license components for the mvn-asciidoctor-gradle-plugin package.
Group: Default

%description license
license components for the mvn-asciidoctor-gradle-plugin package.


%prep
%setup -q -n asciidoctor-gradle-plugin-release_1_5_3

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-asciidoctor-gradle-plugin
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-asciidoctor-gradle-plugin/LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/asciidoctor/asciidoctor-gradle-plugin/1.5.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/asciidoctor/asciidoctor-gradle-plugin/1.5.3/asciidoctor-gradle-plugin-1.5.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/asciidoctor/asciidoctor-gradle-plugin/1.5.3
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/asciidoctor/asciidoctor-gradle-plugin/1.5.3/asciidoctor-gradle-plugin-1.5.3.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/asciidoctor/asciidoctor-gradle-plugin/1.5.3/asciidoctor-gradle-plugin-1.5.3.jar
/usr/share/java/.m2/repository/org/asciidoctor/asciidoctor-gradle-plugin/1.5.3/asciidoctor-gradle-plugin-1.5.3.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-asciidoctor-gradle-plugin/LICENSE.txt
